import { Jost } from "next/font/google";
import "./globals.css";
import styles from "./style.module.css"
import Header from "../../components/header";
import Footer from "../../components/footer";
const jost = Jost({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: "DESIGNO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className={jost.className}>
      <body className={styles.container}>
       <Header/>
        <div className="flex justify-center">{children}  </div>   
        <Footer  className="flex-grow"/>
        </body>

    </html>
  );
}
